### PR TITLE
Update to Font Awesome 4.6.1

### PR DESCRIPTION
**Pull request by mjc-gh**

### CODE REVIEW

**Comment by mjc-gh** [comment]
@tadast can I get rubygems ownership of this gem by any chance?

**Comment by tadast** [comment]
Hi, I'm not maintaining this anymore, so possibly. What's your rubygems ID?

**Comment by mjc-gh** [comment]
Same as my Github: mikeycgto

I would be happy to take over maintainership of this gem.

On Wed, May 4, 2016 at 12:22 PM, Tadas Tamošauskas
notifications@github.com wrote:

> Hi, I'm not maintaining this anymore, so possibly. What's your rubygems ID?
> On Wed, 4 May 2016 at 22:53, Michael Coyne notifications@github.com wrote:
> 
> > @tadast https://github.com/tadast can I get rubygems ownership of this
> > gem by any chance?
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/tadast/fontawesome-rails/pull/1#issuecomment-216910051
> > 
> > ## 
> > 
> > Tadas
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub

## 

http://about.michaeljcoyne.me

**Comment by tadast** [comment]
@mikeycgto I've added you as a collaborator both here on GH and on rubygems

**Comment by tadast** [comment]
@mikeycgto shall we merge and publish this? The changes look good to me

**Comment by mjc-gh** [comment]
Yeah sure. I can it tomorrow if you'd like (and push a new rubygems version)

http://michaeljcoyne.me

**Pull request merged**
